// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzj1EQxu0AmMNC0BPkIIJDy3ZrT32JVR4',
    appId: '1:919799784604:web:4a907b6b3af34869ff3959',
    messagingSenderId: '919799784604',
    projectId: 'colorsofearth-e60aa',
    authDomain: 'colorsofearth-e60aa.firebaseapp.com',
    storageBucket: 'colorsofearth-e60aa.appspot.com',
    measurementId: 'G-JNWGY9JZ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw-CitRRqwIgAOmkB7fvys9qt4wCGY6Fk',
    appId: '1:919799784604:android:7ebebb4a3cccca9bff3959',
    messagingSenderId: '919799784604',
    projectId: 'colorsofearth-e60aa',
    storageBucket: 'colorsofearth-e60aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvr1F5hQ1rFgTJFL1xoKT7yXpGKOMAsLg',
    appId: '1:919799784604:ios:8f217c898d521628ff3959',
    messagingSenderId: '919799784604',
    projectId: 'colorsofearth-e60aa',
    storageBucket: 'colorsofearth-e60aa.appspot.com',
    iosBundleId: 'com.example.colorsOfEarth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvr1F5hQ1rFgTJFL1xoKT7yXpGKOMAsLg',
    appId: '1:919799784604:ios:8f217c898d521628ff3959',
    messagingSenderId: '919799784604',
    projectId: 'colorsofearth-e60aa',
    storageBucket: 'colorsofearth-e60aa.appspot.com',
    iosBundleId: 'com.example.colorsOfEarth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzj1EQxu0AmMNC0BPkIIJDy3ZrT32JVR4',
    appId: '1:919799784604:web:2050a196ccfb2a0fff3959',
    messagingSenderId: '919799784604',
    projectId: 'colorsofearth-e60aa',
    authDomain: 'colorsofearth-e60aa.firebaseapp.com',
    storageBucket: 'colorsofearth-e60aa.appspot.com',
    measurementId: 'G-HVGRVE9PVT',
  );
}
